INSERT INTO ('ID','zonaID','descripcion','extID','fecha_creacion','fecha_modificacion','actual') 
VALUES (
    
1	AZUAY
2	BOLIVAR
3	CAÑAR
4	CARCHI
5	COTOPAXI
6	CHIMBORAZO
7	EL ORO
8	ESMERALDAS
9	GUAYAS
10	IMBABURA
11	LOJA
12	LOS RIOS
13	MANABI
14	MORONA SANTIAGO
15	NAPO
16	PASTAZA
17	PICHINCHA
18	TUNGURAHUA
19	ZAMORA CHINCHIPE
20	GALAPAGOS
21	SUCUMBIOS
22	ORELLANA
23	SANTO DOMINGO DE LOS TSACHILAS
24	SANTA ELENA
90	ZONAS NO DELIMITADAS
